// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blzyinnqusmjwquhlivr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsenlpbm5xdXNtandxdWhsaXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTIwNzIsImV4cCI6MjA2OTA4ODA3Mn0.sLrFdD9gu8r6-kzzhgifmfH8XCTubp-Q52uUEGTUSnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});